/* DROP DATABASE IF EXISTS BOUQUETS_SERVICE; */
/* CREATE DATABASE BOUQUETS_SERVICE; */
DROP TABLE IF EXISTS FLOWER_IN_BOUQUET;
DROP TABLE IF EXISTS FLOWER;
DROP TABLE  IF EXISTS BOUQUET;
DROP TABLE IF EXISTS ORD;
DROP TABLE IF EXISTS USERS;


DROP TYPE IF EXISTS BOUQUET_TYPE;
DROP TYPE IF EXISTS FLOWER_COLOR;
DROP TYPE IF EXISTS FLOWER_NAME;
DROP TYPE IF EXISTS ORDER_STATUS;
DROP TYPE IF EXISTS ROLE;

CREATE TYPE ROLE AS ENUM ('USER', 'ADMIN');
CREATE TYPE BOUQUET_TYPE AS ENUM ('ROUND', 'CASCADE', 'FLAME', 'JAPANESE', 'WEDDING');
CREATE TYPE FLOWER_COLOR AS ENUM ('RED', 'YELLOW', 'BLUE', 'PINK', 'ORANGE', 'BROWN', 'WHITE', 'PURPLE', 'BLACK');
CREATE TYPE FLOWER_NAME AS ENUM ('ROZE', 'ASTER', 'PEONY', 'TULIP', 'CHAMOMILE', 'LILAC', 'CHRYSANTHEMUM');
CREATE TYPE ORDER_STATUS AS ENUM ('NOT_CONFIRMED', 'CONFIRMED', 'IN_PROCESS', 'ASSEMBLED', 'DELIVERED');

CREATE TABLE IF NOT EXISTS USERS(
                                    USERS_ID SERIAL PRIMARY KEY,
                                    FIRST_NAME VARCHAR(100) NOT NULL,
                                    LAST_NAME VARCHAR(100) NOT NULL,
                                    EMAIL VARCHAR(100) NOT NULL,
                                    PASSWORD VARCHAR(30) NOT NULL,
                                    ROLE ROLE NOT NULL
);

CREATE TABLE IF NOT EXISTS ORD(
                                  ORD_ID SERIAL PRIMARY KEY,
                                  ADDRESS VARCHAR(100) NOT NULL,
                                  PHONE_NUMBER VARCHAR(9),
                                  STATUS ORDER_STATUS NOT NULL,
                                  FK_USERS BIGINT NOT NULL,
                                  FOREIGN KEY(FK_USERS) REFERENCES USERS(USERS_ID)
                                      MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BOUQUET(
                                      BOUQUET_ID SERIAL PRIMARY KEY,
                                      TYPE BOUQUET_TYPE NOT NULL,
                                      FK_ORD BIGINT NOT NULL,
                                      FOREIGN KEY(FK_ORD) REFERENCES ORD(ORD_ID)
                                          MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FLOWER(
                                     FLOWER_ID SERIAL PRIMARY KEY,
                                     NAME FLOWER_NAME NOT NULL,
                                     LENGTH SMALLINT NOT NULL,
                                     COLOR FLOWER_COLOR NOT NULL,
                                     QUALITY INTEGER NOT NULL,
                                     PRICE SMALLINT NOT NULL,
                                     FK_BOUQUET BIGINT DEFAULT NULL,
                                     FOREIGN KEY(FK_BOUQUET) REFERENCES BOUQUET(BOUQUET_ID)
                                         MATCH SIMPLE ON UPDATE NO ACTION ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS FLOWER_IN_BOUQUET(
                                                FLOWER_IN_BOUQUET_ID SERIAL PRIMARY KEY,
                                                QUALITY INTEGER NOT NULL,
                                                FK_BOUQUET BIGINT NOT NULL,
                                                FK_FLOWER BIGINT NOT NULL,
                                                FOREIGN KEY(FK_BOUQUET) REFERENCES BOUQUET(BOUQUET_ID),
                                                FOREIGN KEY(FK_FLOWER) REFERENCES FLOWER(FLOWER_ID)
                                                    MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
);


INSERT INTO USERS(FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, ROLE) VALUES ('Андрей', 'Панас', 'sloydeath@mail.ru', 'pa123321', 'ADMIN');
INSERT INTO USERS(FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, ROLE) VALUES ('Вероника', 'Печень', 'nika.henn@mail.ru', 'fsidg34', 'USER');
INSERT INTO USERS(FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, ROLE) VALUES ('Данила', 'Скаков', 'sk.dan.2000@mail.ru', 'danskakov2000', 'USER');


INSERT INTO ORD(ADDRESS, PHONE_NUMBER, STATUS, FK_USERS) VALUES ('Энгельса 111-5', '447013314', 'NOT_CONFIRMED', 1);
INSERT INTO ORD(ADDRESS, PHONE_NUMBER, STATUS, FK_USERS) VALUES ('Кижеватова 148-34', '295708528', 'ASSEMBLED', 3);
INSERT INTO ORD(ADDRESS, PHONE_NUMBER, STATUS, FK_USERS) VALUES ('Строителей 45-12', '338568204', 'DELIVERED', 2);

INSERT INTO BOUQUET(TYPE, FK_ORD) VALUES ('ROUND', 2);
INSERT INTO BOUQUET(TYPE, FK_ORD) VALUES ('CASCADE', 1);
INSERT INTO BOUQUET(TYPE, FK_ORD) VALUES ('JAPANESE', 3);


INSERT INTO FLOWER(NAME, LENGTH, COLOR, QUALITY, PRICE, FK_BOUQUET) VALUES ('ROZE', 60, 'RED', 10,  5, 1);
INSERT INTO FLOWER(NAME, LENGTH, COLOR, QUALITY, PRICE, FK_BOUQUET) VALUES ('ROZE', 40, 'WHITE', 10, 7, 2);
INSERT INTO FLOWER(NAME, LENGTH, COLOR, QUALITY, PRICE, FK_BOUQUET) VALUES ('CHAMOMILE', 40, 'WHITE', 10, 2.5, 2);
INSERT INTO FLOWER(NAME, LENGTH, COLOR, QUALITY, PRICE, FK_BOUQUET) VALUES ('CHRYSANTHEMUM', 60, 'PINK', 10, 6, 1);
INSERT INTO FLOWER(NAME, LENGTH, COLOR, QUALITY, PRICE, FK_BOUQUET) VALUES ('CHRYSANTHEMUM', 50, 'RED', 10, 6.5, 3);
INSERT INTO FLOWER(NAME, LENGTH, COLOR, QUALITY, PRICE, FK_BOUQUET) VALUES ('LILAC' , 50, 'PURPLE', 10, 2, 3);
INSERT INTO FLOWER(NAME, LENGTH, COLOR, QUALITY, PRICE, FK_BOUQUET) VALUES ('TULIP' , 60, 'RED', 10, 3, 1);
INSERT INTO FLOWER(NAME, LENGTH, COLOR, QUALITY, PRICE, FK_BOUQUET) VALUES ('TULIP' , 60, 'BLACK', 10, 3, NULL);
INSERT INTO FLOWER(NAME, LENGTH, COLOR, QUALITY, PRICE, FK_BOUQUET) VALUES ('PEONY' , 60, 'WHITE', 10, 3, NULL);
INSERT INTO FLOWER(NAME, LENGTH, COLOR, QUALITY, PRICE, FK_BOUQUET) VALUES ('ROZE', 40, 'PINK', 10, 5, NULL);


SELECT * FROM USERS;
SELECT * FROM ORD;
SELECT * FROM BOUQUET;
SELECT * FROM FLOWER;
SELECT * FROM FLOWER_IN_BOUQUET;